FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
EXPOSE 8080
WORKDIR /build
COPY . .
RUN dotnet restore
RUN dotnet build "ProductFrontServer.csproj" -c Release -o /app
# Stage 2
FROM build as publish
RUN dotnet publish "ProductFrontServer.csproj" -c Release -o /app


#Angular build
FROM node as nodebuilder

# set working directory
RUN mkdir /usr/src/app
WORKDIR /usr/src/app

# add `/usr/src/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY ClientApp/package.json /usr/src/app/package.json
RUN npm install
RUN npm install -g @angular/cli@1.7.0 --unsafe

# add app

COPY ClientApp/. /usr/src/app

RUN npm run build

#End Angular build

# Stage 3
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS final
WORKDIR /app
COPY --from=publish /app .
RUN mkdir -p /app/ClientApp/dist
COPY --from=nodebuilder /usr/src/app/dist/. /app/ClientApp/dist/
CMD ASPNETCORE_URLS=http://*:$PORT
ENTRYPOINT ["dotnet", "ProductFrontServer.dll"]