import { SubCategoryCard } from "../entities/subCategory-card";

export const SubCategoriesMock : Array<SubCategoryCard> = [
    {
        name:"Quilha",
        categoryId:"qui",
        image:"https://www.kaluasup.com.br/wp-content/uploads/2015/12/prancha-sup-azul-madeira-5.png"
    },
    {
        name:"Capas",
        categoryId:"qui",
        image:"https://www.kaluasup.com.br/wp-content/uploads/2015/12/prancha-sup-azul-madeira-5.png"
    },
    {
        name:"Parafina",
        categoryId:"qui",
        image:"https://www.kaluasup.com.br/wp-content/uploads/2015/12/prancha-sup-azul-madeira-5.png"
    },
    {
        name:"Parafina",
        categoryId:"qui",
        image:"https://www.kaluasup.com.br/wp-content/uploads/2015/12/prancha-sup-azul-madeira-5.png"
    },
    {
        name:"Parafina",
        categoryId:"qui",
        image:"https://www.kaluasup.com.br/wp-content/uploads/2015/12/prancha-sup-azul-madeira-5.png"
    },
    {
        name:"Parafina",
        categoryId:"qui",
        image:"https://www.kaluasup.com.br/wp-content/uploads/2015/12/prancha-sup-azul-madeira-5.png"
    },
    {
        name:"Parafina",
        categoryId:"qui",
        image:"https://www.kaluasup.com.br/wp-content/uploads/2015/12/prancha-sup-azul-madeira-5.png"
    }
]